


sudo -u postgres psql postgres

sudo -u postgres createuser root

sudo createdb readLogs

sudo psql readLogs

SELECT datname FROM pg_database WHERE datistemplate = false;


CREATE USER reader_logs WITH PASSWORD 'temporal1';

CREATE SCHEMA CONTAINER_LOGS_DATA  AUTHORIZATION reader_logs;


-- CREATE SEQUENCES
CREATE SEQUENCE id_pais_app;
CREATE SEQUENCE id_servicio;
CREATE SEQUENCE id_respuesta;
CREATE SEQUENCE id_log;
CREATE SEQUENCE id_BASIC_LOGS;
CREATE SEQUENCE id_file_loaded;


-- CREATE TABLES

SELECT table_catalog ,table_schema ,table_name,table_type  FROM information_schema.tables WHERE table_schema = 'container_logs_data'


CREATE TABLE CONTAINER_LOGS_DATA.FILES_LOADED (ID integer  PRIMARY KEY DEFAULT nextval('id_file_loaded'), NAME varchar(200) NOT NULL UNIQUE);


ALTER SEQUENCE id_BASIC_LOGS RESTART WITH 1;

CREATE TABLE CONTAINER_LOGS_DATA.BASIC_LOGS (
ID integer DEFAULT nextval('id_BASIC_LOGS'), timeStamp TIMESTAMP NOT NULL  , NAME_file varchar(200) not null, elapsed INTEGER ,	label VARCHAR(1000) NOT NULL,	responseCode INTEGER NOT NULL,	responseMessage VARCHAR(100) NOT NULL, 	threadName VARCHAR(1000) NOT NULL,	dataType VARCHAR(1000) NOT NULL,	success VARCHAR(1000) NOT NULL,	failureMessage VARCHAR(1000) NOT NULL,	bytes INTEGER NOT NULL, 	Latency INTEGER NOT NULL,primary key (timeStamp, NAME_file));





CREATE TABLE CONTAINER_LOGS_DATA.PAIS_APP (ID integer CONSTRAINT ID_PAIS_APP PRIMARY KEY DEFAULT nextval('id_pais_app'),PAIS varchar(20) NOT NULL,APP varchar(20) NOT NULL);

CREATE TABLE CONTAINER_LOGS_DATA.SERVICIO (ID integer CONSTRAINT ID_SERVICIO PRIMARY KEY DEFAULT nextval('id_servicio'),ID_PAIS_APP  INTEGER NOT NULL ,SERVICIO VARCHAR(10) NOT NULL,CONSTRAINT fk1 FOREIGN KEY (ID_PAIS_APP) REFERENCES CONTAINER_LOGS_DATA.PAIS_APP (ID) );

CREATE TABLE CONTAINER_LOGS_DATA.RESPUESTA(ID integer CONSTRAINT ID_RESPUESTA PRIMARY KEY DEFAULT nextval('id_respuesta'),CODIGO_RESPUESTA INTEGER NOT NULL, MENSAJE_RESPUESTA VARCHAR(20) NOT NULL);

CREATE TABLE CONTAINER_LOGS_DATA.LOGS(ID integer CONSTRAINT ID_LOG PRIMARY KEY DEFAULT nextval('id_log'),ID_SERVICIO INTEGER NOT NULL,ID_RESPUESTA INTEGER NOT NULL, URL_RESPUESTA VARCHAR (10000) NOT NULL,Fecha  DATE NOT NULL UNIQUE,Traza VARCHAR (1000) NOT NULL,Tiempo_respuesta INTEGER,CONSTRAINT fk2_ FOREIGN KEY (ID_SERVICIO ) REFERENCES CONTAINER_LOGS_DATA.SERVICIO (ID),CONSTRAINT fk3 FOREIGN KEY (ID_RESPUESTA)  REFERENCES CONTAINER_LOGS_DATA.RESPUESTA (ID));





-- DROP
DROP TABLE CONTAINER_LOGS_DATA.PAIS_APP CASCADE;
DROP TABLE CONTAINER_LOGS_DATA.LOGS CASCADE;
DROP TABLE CONTAINER_LOGS_DATA.RESPUESTA CASCADE;
DROP TABLE CONTAINER_LOGS_DATA.SERVICIOS CASCADE;
DROP TABLE CONTAINER_LOGS_DATA.SERVICIO CASCADE;

